### ISSUE TITLE
How use graph_to_txt?

### ISSUE THREAD

**Issue by IlyaEp** [JetBrains-Research/CFPQ_Data#59]
Hello,

 I want to get a graph from a dataset in a txt file. To do this, I wrote a script like this:
```cython
import cfpq_data
g = cfpq_data.graph_from_dataset("generations")
path = cfpq_data.graph_to_txt(g, "test.txt")
```

But in the test.txt file I get something like this:
```
'N1a0fdccf1e5747358d788032136b2d3a' 'http://www.w3.org/1999/02/22-rdf-syntax-ns#first' 'N5b1227cd9d554e6b8376780df8c0ac4b'
'N1a0fdccf1e5747358d788032136b2d3a' 'http://www.w3.org/1999/02/22-rdf-syntax-ns#rest' 'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
'N5b1227cd9d554e6b8376780df8c0ac4b' 'http://www.w3.org/2002/07/owl#someValuesFrom' 'Nf6e96ad96dee4cc380a425a39571412b'
'N5b1227cd9d554e6b8376780df8c0ac4b' 'http://www.w3.org/2002/07/owl#onProperty' 'http://www.owl-ontologies.com/generations.owl#hasChild'
...
```
Please tell me where I am wrong. Thank you

**Comment by vdshk** [comment]
Hi, @IlyaEp!

Thanks for your interest in cfpq_data!

Now cfpq_data converts the MultiDiGraph to a text file, writing each labeled edge as a triple (node, edge label, node) to txt file.
This way, you will get the quoted triplets in the test.txt file in the same format as you mentioned.
Because the corresponding edges in the RDF graph look exactly like this.

And the question is, what format did you expect to see?

**Comment by IlyaEp** [comment]
Thanks for your reply!

I expected the vertices in the txt file to be numbered as they were in older versions of *CFPQ_Data*. It would be very helpful.

**Comment by vdshk** [comment]
In the latest version, you can get this format this way.

```Python
import cfpq_data
g = cfpq_data.graph_from_dataset("generations")
g = cfpq_data.nodes_to_integers(g)
path = cfpq_data.graph_to_txt(g, "test.txt", quoting=False)
```

You can also use [graph utilities](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/graphs_utils.html) to convert the graph to the format you want.

**Comment by IlyaEp** [comment]
Thank you!
